# Generated by Django 5.1.4 on 2024-12-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DdosPaciente',
            new_name='DadosPaciente',
        ),
    ]
